# Get Stories
GET {{host}}:{{port}}/stories
###

# Get Story by ID
GET {{host}}:{{port}}/stories/2
###

# Add Story
POST {{host}}:{{port}}/stories
Content-Type: application/json

{
    "userId": "sleepy-gray-raccoon",
    "title": "Eine neue Geschichte",
    "body": "Heute war ein toller Tag. Ich war im Zoo und habe eine neue Geschichte gefunden."
}
###
